"""empty message

Revision ID: 14294b8981d7
Revises: 8169b0a2c489
Create Date: 2016-04-23 19:42:34.736050

"""

# revision identifiers, used by Alembic.
revision = '14294b8981d7'
down_revision = '8169b0a2c489'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wifi_access_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SSID', sa.Text(), nullable=True),
    sa.Column('BSSID', sa.Text(), nullable=True),
    sa.Column('RSSI', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wifi_access_points')
    ### end Alembic commands ###
