"""empty message

Revision ID: 17687424de84
Revises: 30337f70fadc
Create Date: 2016-04-25 00:10:59.391099

"""

# revision identifiers, used by Alembic.
revision = '17687424de84'
down_revision = '30337f70fadc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_loc', sa.Column('GPSAccu', sa.Float(), nullable=True))
    op.add_column('tag_loc', sa.Column('GPSAlt', sa.Float(), nullable=True))
    op.add_column('tag_loc', sa.Column('GPSLat', sa.Float(), nullable=True))
    op.add_column('tag_loc', sa.Column('GPSLong', sa.Float(), nullable=True))
    op.drop_column('tag_loc', 'GPSJSON')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_loc', sa.Column('GPSJSON', mysql.FLOAT(), nullable=True))
    op.drop_column('tag_loc', 'GPSLong')
    op.drop_column('tag_loc', 'GPSLat')
    op.drop_column('tag_loc', 'GPSAlt')
    op.drop_column('tag_loc', 'GPSAccu')
    ### end Alembic commands ###
