"""empty message

Revision ID: 1b77e3bae583
Revises: 814469bf0975
Create Date: 2016-04-14 21:04:35.228429

"""

# revision identifiers, used by Alembic.
revision = '1b77e3bae583'
down_revision = '814469bf0975'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_loc', sa.Column('altitude', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gps_loc', 'altitude')
    ### end Alembic commands ###
