"""empty message

Revision ID: 25b8da04ae48
Revises: 788cb0c26beb
Create Date: 2016-03-28 16:57:50.693757

"""

# revision identifiers, used by Alembic.
revision = '25b8da04ae48'
down_revision = '788cb0c26beb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('floordata', 'time', existing_type=sa.Text(), type_=sa.Float(16, 5))
    op.alter_column('floordata', 'gpsSpeed', existing_type=sa.Text(), type_=sa.Float(18, 14))
    op.alter_column('floordata', 'gpsCourse', existing_type=sa.Text(), type_=sa.Float(18, 14))
    op.alter_column('floordata', 'gpsAccuracyHor', existing_type=sa.Text(), type_=sa.Float(18, 14))
    op.alter_column('floordata', 'gpsAccuracyVert', existing_type=sa.Text(), type_=sa.Float(18, 14))
    op.alter_column('floordata', 'alt', existing_type=sa.Text(), type_=sa.Float(18, 14))
    op.alter_column('floordata', 'altPressure', existing_type=sa.Text(), type_=sa.Float(18, 14))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    op.alter_column('floordata', 'time', existing_type=a.Float(16, 5), type_=sa.Text())
    op.alter_column('floordata', 'gpsSpeed', existing_type=sa.Float(18, 14), type_=sa.Text())
    op.alter_column('floordata', 'gpsCourse', existing_type=sa.Float(18, 14), type_=sa.Text())
    op.alter_column('floordata', 'gpsAccuracyHor', existing_type=sa.Float(18, 14), type_=sa.Text())
    op.alter_column('floordata', 'gpsAccuracyVert', existing_type=sa.Float(18, 14), type_=sa.Text())
    op.alter_column('floordata', 'alt', existing_type=sa.Float(18, 14), type_=sa.Text())
    op.alter_column('floordata', 'altPressure', existing_type=sa.Float(18, 14), type_=sa.Text())
