"""empty message

Revision ID: 2a5a393904f6
Revises: baa7046f44d9
Create Date: 2016-04-04 03:39:57.988554

"""

# revision identifiers, used by Alembic.
revision = '2a5a393904f6'
down_revision = 'baa7046f44d9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell_towerWCDMA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cellId', sa.Integer(), nullable=True),
    sa.Column('locationAreaCode', sa.Integer(), nullable=True),
    sa.Column('mobileCountryCode', sa.Integer(), nullable=True),
    sa.Column('mobileNetworkCode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell_tower2G',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cellId', sa.Integer(), nullable=True),
    sa.Column('locationAreaCode', sa.Integer(), nullable=True),
    sa.Column('mobileCountryCode', sa.Integer(), nullable=True),
    sa.Column('mobileNetworkCode', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('signalStrength', sa.Integer(), nullable=True),
    sa.Column('timingAdvance', sa.Float(), nullable=True),
    sa.Column('carrier', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gps_loc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Text(), nullable=True),
    sa.Column('accuracy', sa.Text(), nullable=True),
    sa.Column('indoor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('floor_predictions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_predictions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('mid_alt', mysql.FLOAT(), nullable=True),
    sa.Column('start_alt', mysql.FLOAT(), nullable=True),
    sa.Column('direction', mysql.TEXT(), nullable=True),
    sa.Column('end_time', mysql.TEXT(), nullable=True),
    sa.Column('floor', mysql.FLOAT(), nullable=True),
    sa.Column('start_time', mysql.TEXT(), nullable=True),
    sa.Column('mid_time', mysql.TEXT(), nullable=True),
    sa.Column('end_alt', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('gps_loc')
    op.drop_table('cell_tower2G')
    op.drop_table('cell_towerWCDMA')
    ### end Alembic commands ###
