"""empty message

Revision ID: 2e1f354de74e
Revises: 67eb2f70448e
Create Date: 2016-04-23 19:40:31.786669

"""

# revision identifiers, used by Alembic.
revision = '2e1f354de74e'
down_revision = '67eb2f70448e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_loc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('indoor', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wifi_access_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SSID', sa.Text(), nullable=True),
    sa.Column('BSSID', sa.Text(), nullable=True),
    sa.Column('RSSI', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wifi_access_points')
    op.drop_table('gps_loc')
    ### end Alembic commands ###
