"""empty message

Revision ID: 30337f70fadc
Revises: ca0fd3521db3
Create Date: 2016-04-24 23:29:38.815823

"""

# revision identifiers, used by Alembic.
revision = '30337f70fadc'
down_revision = 'ca0fd3521db3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_loc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('indoorFlag', sa.Boolean(), nullable=True),
    sa.Column('GPSJSON', sa.Float(), nullable=True),
    sa.Column('wifiJSON', sa.Text(), nullable=True),
    sa.Column('cellTowerJSON', sa.Text(), nullable=True),
    sa.Column('addr_id', sa.Integer(), nullable=True),
    sa.Column('addrJSON', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['addr_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_loc')
    ### end Alembic commands ###
