"""empty message

Revision ID: 3aadbde256b1
Revises: b9b31989e8e5
Create Date: 2016-05-07 16:52:18.601436

"""

# revision identifiers, used by Alembic.
revision = '3aadbde256b1'
down_revision = 'b9b31989e8e5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cell_tower')
    op.drop_table('cell_towerWCDMA')
    op.drop_table('cell_tower2G')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell_tower2G',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cellId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('locationAreaCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mobileCountryCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mobileNetworkCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('signalStrength', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timingAdvance', mysql.FLOAT(), nullable=True),
    sa.Column('carrier', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('cell_towerWCDMA',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cellId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('locationAreaCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mobileCountryCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mobileNetworkCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('carrier', mysql.TEXT(), nullable=True),
    sa.Column('signalStrength', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timingAdvance', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('cell_tower',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cellId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('locationAreaCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('homeMobileCountryCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('homeMobileNetworkCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('radioType', mysql.TEXT(), nullable=True),
    sa.Column('gsm', mysql.TEXT(), nullable=True),
    sa.Column('cdma', mysql.TEXT(), nullable=True),
    sa.Column('wcdma', mysql.TEXT(), nullable=True),
    sa.Column('lte', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
