"""empty message

Revision ID: 3c5058b46396
Revises: a6a96cb09a82
Create Date: 2016-04-24 23:05:29.246224

"""

# revision identifiers, used by Alembic.
revision = '3c5058b46396'
down_revision = 'a6a96cb09a82'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('street', sa.Text(), nullable=True))
    op.add_column('addresses', sa.Column('zip', sa.Text(), nullable=True))
    op.drop_column('addresses', 'streetAddr')
    op.drop_column('addresses', 'zipcode')
    op.drop_column('addresses', 'district')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('district', mysql.TEXT(), nullable=True))
    op.add_column('addresses', sa.Column('zipcode', mysql.TEXT(), nullable=True))
    op.add_column('addresses', sa.Column('streetAddr', mysql.TEXT(), nullable=True))
    op.drop_column('addresses', 'zip')
    op.drop_column('addresses', 'street')
    ### end Alembic commands ###
