"""empty message

Revision ID: 50a549247288
Revises: 9f53f6209f96
Create Date: 2016-04-17 18:18:34.511488

"""

# revision identifiers, used by Alembic.
revision = '50a549247288'
down_revision = '9f53f6209f96'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'addresses_ibfk_1', 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'user_id')
    op.add_column('tag_loc', sa.Column('addr_id', sa.Integer(), nullable=True))
    op.add_column('tag_loc', sa.Column('cellTower2GJson', sa.Text(), nullable=True))
    op.add_column('tag_loc', sa.Column('cellTowerWCDMAJson', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'tag_loc', 'addresses', ['addr_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_loc', type_='foreignkey')
    op.drop_column('tag_loc', 'cellTowerWCDMAJson')
    op.drop_column('tag_loc', 'cellTower2GJson')
    op.drop_column('tag_loc', 'addr_id')
    op.add_column('addresses', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'addresses_ibfk_1', 'addresses', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###
