"""empty message

Revision ID: 5274b0f2bf09
Revises: None
Create Date: 2016-03-27 14:50:49.628740

"""

# revision identifiers, used by Alembic.
revision = '5274b0f2bf09'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floordata', sa.Column('deviceId', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('floordata', 'deviceId')
    ### end Alembic commands ###
