"""empty message

Revision ID: 67eb2f70448e
Revises: bfd17fd48da9
Create Date: 2016-04-23 19:40:09.540171

"""

# revision identifiers, used by Alembic.
revision = '67eb2f70448e'
down_revision = 'bfd17fd48da9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wifi_access_points')
    op.drop_table('gps_loc')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_loc',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('latitude', mysql.TEXT(), nullable=True),
    sa.Column('longitude', mysql.TEXT(), nullable=True),
    sa.Column('accuracy', mysql.TEXT(), nullable=True),
    sa.Column('indoor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('altitude', mysql.FLOAT(), nullable=True),
    sa.Column('timestamp', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('wifi_access_points',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('SSID', mysql.TEXT(), nullable=True),
    sa.Column('BSSID', mysql.TEXT(), nullable=True),
    sa.Column('frequency', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.TEXT(), nullable=True),
    sa.Column('RSSI', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
