"""empty message

Revision ID: 788cb0c26beb
Revises: 5274b0f2bf09
Create Date: 2016-03-28 16:53:18.845064

"""

# revision identifiers, used by Alembic.
revision = '788cb0c26beb'
down_revision = '5274b0f2bf09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floordata', sa.Column('latitude', sa.Float(precision=10, asdecimal=6), nullable=True))
    op.add_column('floordata', sa.Column('longitude', sa.Float(precision=10, asdecimal=6), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('floordata', 'longitude')
    op.drop_column('floordata', 'latitude')
    ### end Alembic commands ###
