"""empty message

Revision ID: 814469bf0975
Revises: 9475685f5793
Create Date: 2016-04-14 17:54:57.101882

"""

# revision identifiers, used by Alembic.
revision = '814469bf0975'
down_revision = '9475685f5793'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wifi_access_points', 'distance')
    op.drop_column('wifi_access_points', 'distanceSd')
    op.drop_column('wifi_access_points', 'isConnected')
    op.drop_column('wifi_access_points', 'capabilities')
    op.drop_column('wifi_access_points', 'level')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wifi_access_points', sa.Column('level', mysql.TEXT(), nullable=True))
    op.add_column('wifi_access_points', sa.Column('capabilities', mysql.TEXT(), nullable=True))
    op.add_column('wifi_access_points', sa.Column('isConnected', mysql.TEXT(), nullable=True))
    op.add_column('wifi_access_points', sa.Column('distanceSd', mysql.TEXT(), nullable=True))
    op.add_column('wifi_access_points', sa.Column('distance', mysql.TEXT(), nullable=True))
    ### end Alembic commands ###
