"""empty message

Revision ID: 88d43767cdf0
Revises: 14294b8981d7
Create Date: 2016-04-24 21:26:00.329605

"""

# revision identifiers, used by Alembic.
revision = '88d43767cdf0'
down_revision = '14294b8981d7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell_tower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cellId', sa.Integer(), nullable=True),
    sa.Column('locationAreaCode', sa.Integer(), nullable=True),
    sa.Column('homeMobileCountryCode', sa.Integer(), nullable=True),
    sa.Column('homeMobileNetworkCode', sa.Integer(), nullable=True),
    sa.Column('radioType', sa.Text(), nullable=True),
    sa.Column('gsm', sa.Text(), nullable=True),
    sa.Column('cdma', sa.Text(), nullable=True),
    sa.Column('wcdma', sa.Text(), nullable=True),
    sa.Column('lte', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'addresses', sa.Column('streetAddr', sa.Text(), nullable=True))
    op.add_column(u'addresses', sa.Column('zipcode', sa.Text(), nullable=True))
    op.add_column(u'tag_loc', sa.Column('cellTowerJson', sa.Text(), nullable=True))
    op.drop_column(u'tag_loc', 'cellTowerWCDMAJson')
    op.drop_column(u'tag_loc', 'cellTower2GJson')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'tag_loc', sa.Column('cellTower2GJson', mysql.TEXT(), nullable=True))
    op.add_column(u'tag_loc', sa.Column('cellTowerWCDMAJson', mysql.TEXT(), nullable=True))
    op.drop_column(u'tag_loc', 'cellTowerJson')
    op.drop_column(u'addresses', 'zipcode')
    op.drop_column(u'addresses', 'streetAddr')
    op.drop_table('cell_tower')
    ### end Alembic commands ###
