"""empty message

Revision ID: 9475685f5793
Revises: 2a5a393904f6
Create Date: 2016-04-11 16:07:51.211741

"""

# revision identifiers, used by Alembic.
revision = '9475685f5793'
down_revision = '2a5a393904f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cell_towerWCDMA', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('cell_towerWCDMA', sa.Column('carrier', sa.Text(), nullable=True))
    op.add_column('cell_towerWCDMA', sa.Column('signalStrength', sa.Integer(), nullable=True))
    op.add_column('cell_towerWCDMA', sa.Column('timingAdvance', sa.Float(), nullable=True))
    op.add_column('wifi_access_points', sa.Column('RSSI', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wifi_access_points', 'RSSI')
    op.drop_column('cell_towerWCDMA', 'timingAdvance')
    op.drop_column('cell_towerWCDMA', 'signalStrength')
    op.drop_column('cell_towerWCDMA', 'carrier')
    op.drop_column('cell_towerWCDMA', 'age')
    ### end Alembic commands ###
