"""empty message

Revision ID: 9f53f6209f96
Revises: 7bd84203003b
Create Date: 2016-04-17 17:57:58.634830

"""

# revision identifiers, used by Alembic.
revision = '9f53f6209f96'
down_revision = '7bd84203003b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_loc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('indoorFlag', sa.Boolean(), nullable=True),
    sa.Column('GPSLat', sa.Float(), nullable=True),
    sa.Column('GPSLng', sa.Float(), nullable=True),
    sa.Column('wifiJson', sa.Text(), nullable=True),
    sa.Column('addrJson', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('devices')
    op.drop_table('sensorlog')
    op.drop_table('datapoints')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datapoints',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('value', mysql.TEXT(), nullable=True),
    sa.Column('device_id', mysql.TEXT(), nullable=True),
    sa.Column('data_type', mysql.TEXT(), nullable=True),
    sa.Column('lat', mysql.FLOAT(), nullable=True),
    sa.Column('lon', mysql.FLOAT(), nullable=True),
    sa.Column('value_type', mysql.TEXT(), nullable=True),
    sa.Column('value_unit', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('sensorlog',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('loggingTime', mysql.TEXT(), nullable=True),
    sa.Column('loggingSample', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('identifierForVendor', mysql.TEXT(), nullable=True),
    sa.Column('deviceID', mysql.TEXT(), nullable=True),
    sa.Column('locationTimestamp_since1970', mysql.TEXT(), nullable=True),
    sa.Column('locationLatitude', mysql.TEXT(), nullable=True),
    sa.Column('locationLongitude', mysql.TEXT(), nullable=True),
    sa.Column('locationAltitude', mysql.TEXT(), nullable=True),
    sa.Column('locationSpeed', mysql.TEXT(), nullable=True),
    sa.Column('locationCourse', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('locationVerticalAccuracy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('locationHorizontalAccuracy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('locationFloor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('locationHeadingTimestamp_since1970', mysql.TEXT(), nullable=True),
    sa.Column('locationHeadingX', mysql.TEXT(), nullable=True),
    sa.Column('locationHeadingY', mysql.TEXT(), nullable=True),
    sa.Column('locationHeadingZ', mysql.TEXT(), nullable=True),
    sa.Column('locationTrueHeading', mysql.TEXT(), nullable=True),
    sa.Column('locationMagneticHeading', mysql.TEXT(), nullable=True),
    sa.Column('locationHeadingAccuracy', mysql.TEXT(), nullable=True),
    sa.Column('accelerometerTimestamp_sinceReboot', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('accelerometerAccelerationX', mysql.TEXT(), nullable=True),
    sa.Column('accelerometerAccelerationY', mysql.TEXT(), nullable=True),
    sa.Column('accelerometerAccelerationZ', mysql.TEXT(), nullable=True),
    sa.Column('gyroTimestamp_sinceReboot', mysql.TEXT(), nullable=True),
    sa.Column('gyroRotationX', mysql.TEXT(), nullable=True),
    sa.Column('gyroRotationY', mysql.TEXT(), nullable=True),
    sa.Column('gyroRotationZ', mysql.TEXT(), nullable=True),
    sa.Column('motionTimestamp_sinceReboot', mysql.TEXT(), nullable=True),
    sa.Column('motionYaw', mysql.TEXT(), nullable=True),
    sa.Column('motionRoll', mysql.TEXT(), nullable=True),
    sa.Column('motionPitch', mysql.TEXT(), nullable=True),
    sa.Column('motionRotationRateX', mysql.TEXT(), nullable=True),
    sa.Column('motionRotationRateY', mysql.TEXT(), nullable=True),
    sa.Column('motionRotationRateZ', mysql.TEXT(), nullable=True),
    sa.Column('motionUserAccelerationX', mysql.TEXT(), nullable=True),
    sa.Column('motionUserAccelerationY', mysql.TEXT(), nullable=True),
    sa.Column('motionUserAccelerationZ', mysql.TEXT(), nullable=True),
    sa.Column('motionAttitudeReferenceFrame', mysql.TEXT(), nullable=True),
    sa.Column('motionQuaternionX', mysql.TEXT(), nullable=True),
    sa.Column('motionQuaternionY', mysql.TEXT(), nullable=True),
    sa.Column('motionQuaternionZ', mysql.TEXT(), nullable=True),
    sa.Column('motionQuaternionW', mysql.TEXT(), nullable=True),
    sa.Column('motionGravityX', mysql.TEXT(), nullable=True),
    sa.Column('motionGravityY', mysql.TEXT(), nullable=True),
    sa.Column('motionGravityZ', mysql.TEXT(), nullable=True),
    sa.Column('motionMagneticFieldX', mysql.TEXT(), nullable=True),
    sa.Column('motionMagneticFieldY', mysql.TEXT(), nullable=True),
    sa.Column('motionMagneticFieldZ', mysql.TEXT(), nullable=True),
    sa.Column('motionMagneticFieldCalibrationAccuracy', mysql.TEXT(), nullable=True),
    sa.Column('activityTimestamp_sinceReboot', mysql.TEXT(), nullable=True),
    sa.Column('activity', mysql.TEXT(), nullable=True),
    sa.Column('activityActivityConfidence', mysql.TEXT(), nullable=True),
    sa.Column('activityActivityStartDate', mysql.TEXT(), nullable=True),
    sa.Column('pedometerStartDate', mysql.TEXT(), nullable=True),
    sa.Column('pedometerNumberofSteps', mysql.TEXT(), nullable=True),
    sa.Column('pedometerDistance', mysql.TEXT(), nullable=True),
    sa.Column('pedometerFloorAscended', mysql.TEXT(), nullable=True),
    sa.Column('pedometerFloorDescended', mysql.TEXT(), nullable=True),
    sa.Column('pedometerEndDate', mysql.TEXT(), nullable=True),
    sa.Column('altimeterTimestamp_sinceReboot', mysql.TEXT(), nullable=True),
    sa.Column('altimeterReset', mysql.TEXT(), nullable=True),
    sa.Column('altimeterRelativeAltitude', mysql.TEXT(), nullable=True),
    sa.Column('altimeterPressure', mysql.TEXT(), nullable=True),
    sa.Column('IP_en0', mysql.TEXT(), nullable=True),
    sa.Column('IP_pdp_ip0', mysql.TEXT(), nullable=True),
    sa.Column('deviceOrientation', mysql.TEXT(), nullable=True),
    sa.Column('batteryState', mysql.TEXT(), nullable=True),
    sa.Column('batteryLevel', mysql.TEXT(), nullable=True),
    sa.Column('state', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('devices',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('signal_type', mysql.TEXT(), nullable=True),
    sa.Column('ssid', mysql.TEXT(), nullable=True),
    sa.Column('bssid', mysql.TEXT(), nullable=True),
    sa.Column('rssi', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('tag_loc')
    ### end Alembic commands ###
