"""empty message

Revision ID: a6a96cb09a82
Revises: d1b1ba7ce420
Create Date: 2016-04-24 23:01:43.550827

"""

# revision identifiers, used by Alembic.
revision = 'a6a96cb09a82'
down_revision = 'd1b1ba7ce420'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_loc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('indoorFlag', sa.Boolean(), nullable=True),
    sa.Column('GPSJSON', sa.Float(), nullable=True),
    sa.Column('wifiJSON', sa.Text(), nullable=True),
    sa.Column('cellTowerJSON', sa.Text(), nullable=True),
    sa.Column('addr_id', sa.Integer(), nullable=True),
    sa.Column('addrJson', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['addr_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_loc')
    ### end Alembic commands ###
