"""empty message

Revision ID: b9b31989e8e5
Revises: 17687424de84
Create Date: 2016-05-02 10:39:01.639020

"""

# revision identifiers, used by Alembic.
revision = 'b9b31989e8e5'
down_revision = '17687424de84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_loc', sa.Column('pressure', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag_loc', 'pressure')
    ### end Alembic commands ###
