"""empty message

Revision ID: baa7046f44d9
Revises: 25b8da04ae48
Create Date: 2016-03-28 17:31:16.848128

"""

# revision identifiers, used by Alembic.
revision = 'baa7046f44d9'
down_revision = '25b8da04ae48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('floordata', 'time', existing_type=sa.Float(16, 5), type_=sa.Numeric(precision='16', scale='5'))
    op.alter_column('floordata', 'gpsSpeed', existing_type=sa.Float(18, 14), type_=sa.Numeric(precision='18', scale='14'))
    op.alter_column('floordata', 'gpsCourse', existing_type=sa.Float(18, 14), type_=sa.Numeric(precision='18', scale='14'))
    op.alter_column('floordata', 'gpsAccuracyHor', existing_type=sa.Float(18, 14), type_=sa.Numeric(precision='18', scale='14'))
    op.alter_column('floordata', 'gpsAccuracyVert', existing_type=sa.Float(18, 14), type_=sa.Numeric(precision='18', scale='14'))
    op.alter_column('floordata', 'alt', existing_type=sa.Float(18, 14), type_=sa.Numeric(precision='18', scale='14'))
    op.alter_column('floordata', 'altPressure', existing_type=sa.Float(18, 14), type_=sa.Numeric(precision='18', scale='14'))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('floordata', 'time', existing_type=sa.Numeric(precision='16', scale='5'), type_=sa.Float(16, 5))
    op.alter_column('floordata', 'gpsSpeed', existing_type=sa.Numeric(precision='18', scale='14'), type_=sa.Float(18, 14))
    op.alter_column('floordata', 'gpsCourse', existing_type=sa.Numeric(precision='18', scale='14'), type_=sa.Float(18, 14))
    op.alter_column('floordata', 'gpsAccuracyHor', existing_type=sa.Numeric(precision='18', scale='14'), type_=sa.Float(18, 14))
    op.alter_column('floordata', 'gpsAccuracyVert', existing_type=sa.Numeric(precision='18', scale='14'), type_=sa.Float(18, 14))
    op.alter_column('floordata', 'alt', existing_type=sa.Numeric(precision='18', scale='14'), type_=sa.Float(18, 14))
    op.alter_column('floordata', 'altPressure', existing_type=sa.Numeric(precision='18', scale='14'), type_=sa.Float(18, 14))

    ### end Alembic commands ###
