"""empty message

Revision ID: d1b1ba7ce420
Revises: 60966731f73a
Create Date: 2016-04-24 23:01:35.168160

"""

# revision identifiers, used by Alembic.
revision = 'd1b1ba7ce420'
down_revision = '60966731f73a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_loc')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_loc',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('timestamp', mysql.FLOAT(), nullable=True),
    sa.Column('indoorFlag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('GPSLat', mysql.FLOAT(), nullable=True),
    sa.Column('GPSLng', mysql.FLOAT(), nullable=True),
    sa.Column('wifiJson', mysql.TEXT(), nullable=True),
    sa.Column('addrJson', mysql.TEXT(), nullable=True),
    sa.Column('addr_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cellTowerJson', mysql.TEXT(), nullable=True),
    sa.Column('GPSJSON', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['addr_id'], [u'addresses.id'], name=u'tag_loc_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
